apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-production
  name: frontend-production
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend-production
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-production
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend-production
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend-production
      name: frontend
    spec:
      containers:
      - image: gcr.io/anthos-tech-summit/gcpdemo:40c4f9f9-c3dc-4a02-996c-4d7c257f8f1a
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
        name: webserver
        ports:
        - containerPort: 8080
          name: frontend
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
