# config-management.yaml
apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  # clusterName is required and must be unique among all managed clusters
  clusterName: external-cluster-b
  git:
    syncRepo: https://github.com/bkauf/csp-config-management/
    secretType: none
   # policyDir: "foo-corp"
    policyDir: "hello-namespace/config-root"
    syncBranch: 1.0.0
